version: "3"

services:
# Main service
  naive-eamt:
    image: naive-eamt
    volumes:
      # Copy config
      - ./configuration.ini:/eamt/configuration.ini
      # Mount the downloaded data directory(s)
      - ./data:/eamt/data
    ports:
      - 6100:80
    networks:
      - neamt-net
# MAG services with relevant parameters
  mag_en:
    image: aksw/agdistis:latest
    networks:
      - neamt-net
    profiles: ["mag"]
    volumes:
      # mount index
      - ./data/mag_data/indexdbpedia_en_2016:/usr/local/tomcat/index
      # mount context
      - ./data/mag_data/index_bycontext_en:/usr/local/tomcat/index_bycontext
    mem_limit: 8g
    restart: always
    environment:
      - AGDISTIS_NODE_TYPE=http://dbpedia.org/resource/
      - AGDISTIS_EDGE_TYPE=http://dbpedia.org/ontology/
      - AGDISTIS_BASE_URI=http://dbpedia.org
      - AGDISTIS_CONTEXT=True
  mag_de:
    image: aksw/agdistis:latest
    networks:
      - neamt-net
    profiles: ["mag"]
    volumes:
      # mount index
      - ./data/mag_data/indexdbpedia_de_2016:/usr/local/tomcat/index
      # mount context
      - ./data/mag_data/index_bycontext_de:/usr/local/tomcat/index_bycontext
    mem_limit: 8g
    restart: always
    environment:
      - AGDISTIS_NODE_TYPE=http://de.dbpedia.org/resource/
      - AGDISTIS_EDGE_TYPE=http://dbpedia.org/ontology/
      - AGDISTIS_BASE_URI=http://dbpedia.org
      - AGDISTIS_CONTEXT=True
  mag_fr:
    image: aksw/agdistis:latest
    networks:
      - neamt-net
    profiles: ["mag"]
    volumes:
      # mount index
      - ./data/mag_data/indexdbpedia_fr_2016:/usr/local/tomcat/index
    mem_limit: 8g
    restart: always
    environment:
      - AGDISTIS_NODE_TYPE=http://fr.dbpedia.org/resource/
      - AGDISTIS_EDGE_TYPE=http://dbpedia.org/ontology/
      - AGDISTIS_BASE_URI=http://dbpedia.org
      - AGDISTIS_CONTEXT=False
  mag_es:
    image: aksw/agdistis:latest
    networks:
      - neamt-net
    profiles: ["mag"]
    volumes:
      # mount index
      - ./data/mag_data/indexdbpedia_es_2016:/usr/local/tomcat/index
    mem_limit: 8g
    restart: always
    environment:
      - AGDISTIS_NODE_TYPE=http://es.dbpedia.org/resource/
      - AGDISTIS_EDGE_TYPE=http://dbpedia.org/ontology/
      - AGDISTIS_BASE_URI=http://dbpedia.org
      - AGDISTIS_CONTEXT=False