version: "3.3"

services:
# Main service
  naive-eamt:
    image: naive-eamt
    build: .
    restart: always
    volumes:
      # Copy code
      - ./logs:/neamt/logs
      # Copy config
      - ./configuration.ini:/neamt/configuration.ini
      # Mount the downloaded data directory(s)
      - ./data:/neamt/data
      - ./mt-finetune/ft_models:/neamt/ft_models
      # Mount cache
      - ./cache/huggingface:/root/.cache/huggingface
      - ./cache/flair:/root/.flair
    ports:
      - 6100:80
    networks:
      - neamt-net
    environment:
      - SWC_URL="${SWC_URL}"
      - SWC_AUTH="${SWC_AUTH}"
      - SWC_PID="${SWC_PID}"
  # Libre Translate service
  libretranslate:
    image: libretranslate
    restart: always
    command: ['--host', '0.0.0.0']
    profiles: ["libre_mt"]
    # The port mapping below is only needed for testing/dev purposes. It can be removed safely without affecting any functionality.
    ports:
      - 6120:5000
    networks:
      - neamt-net
  # Helsinki Opus-MT Translate service
  opusmt:
    image: opus-mt
    profiles: ["opus_mt"]
    restart: always
    volumes:
      - ./data/Opus-MT/models:/usr/src/app/models
    # The port mapping below is only needed for testing/dev purposes. It can be removed safely without affecting any functionality.
    #ports:
    #  - 6121:80
    networks:
      - neamt-net
  # MAG services with relevant parameters
  mag-en:
    image: aksw/agdistis:latest
    networks:
      - neamt-net
    profiles: ["mag"]
    # This port mapping is being used by GERBIL (for neamt server only)
    ports:
      - 6131:8080
    volumes:
      # mount index
      - ./data/mag_data/indexdbpedia_en_2016:/usr/local/tomcat/index
      # mount context
      - ./data/mag_data/index_bycontext_en:/usr/local/tomcat/index_bycontext
    mem_limit: 8g
    restart: always
    environment:
      - AGDISTIS_NODE_TYPE=http://dbpedia.org/resource/
      - AGDISTIS_EDGE_TYPE=http://dbpedia.org/ontology/
      - AGDISTIS_BASE_URI=http://dbpedia.org
      - AGDISTIS_CONTEXT=True
  mag-de:
    image: aksw/agdistis:latest
    networks:
      - neamt-net
    profiles: ["mag"]
    # This port mapping is being used by GERBIL (for neamt server only)
    ports:
      - 6132:8080
    volumes:
      # mount index
      - ./data/mag_data/indexdbpedia_de_2016:/usr/local/tomcat/index
      # mount context
      - ./data/mag_data/index_bycontext_de:/usr/local/tomcat/index_bycontext
    mem_limit: 8g
    restart: always
    environment:
      - AGDISTIS_NODE_TYPE=http://de.dbpedia.org/resource/
      - AGDISTIS_EDGE_TYPE=http://dbpedia.org/ontology/
      - AGDISTIS_BASE_URI=http://dbpedia.org
      - AGDISTIS_CONTEXT=True
  mag-fr:
    image: aksw/agdistis:latest
    networks:
      - neamt-net
    profiles: ["mag"]
    # This port mapping is being used by GERBIL (for neamt server only)
    ports:
      - 6133:8080
    volumes:
      # mount index
      - ./data/mag_data/indexdbpedia_fr_2016:/usr/local/tomcat/index
    mem_limit: 8g
    restart: always
    environment:
      - AGDISTIS_NODE_TYPE=http://fr.dbpedia.org/resource/
      - AGDISTIS_EDGE_TYPE=http://dbpedia.org/ontology/
      - AGDISTIS_BASE_URI=http://dbpedia.org
      - AGDISTIS_CONTEXT=False
  mag-es:
    image: aksw/agdistis:latest
    networks:
      - neamt-net
    profiles: ["mag"]
    # This port mapping is being used by GERBIL (for neamt server only)
    ports:
      - 6134:8080
    volumes:
      # mount index
      - ./data/mag_data/indexdbpedia_es_2016:/usr/local/tomcat/index
    mem_limit: 8g
    restart: always
    environment:
      - AGDISTIS_NODE_TYPE=http://es.dbpedia.org/resource/
      - AGDISTIS_EDGE_TYPE=http://dbpedia.org/ontology/
      - AGDISTIS_BASE_URI=http://dbpedia.org
      - AGDISTIS_CONTEXT=False
  mag-it:
    image: aksw/agdistis:latest
    networks:
      - neamt-net
    profiles: ["mag"]
    # This port mapping is being used by GERBIL (for neamt server only)
    ports:
      - 6135:8080
    volumes:
      # mount index
      - ./data/mag_data/indexdbpedia_it_2016:/usr/local/tomcat/index
    mem_limit: 8g
    restart: always
    environment:
      - AGDISTIS_NODE_TYPE=http://it.dbpedia.org/resource/
      - AGDISTIS_EDGE_TYPE=http://dbpedia.org/ontology/
      - AGDISTIS_BASE_URI=http://dbpedia.org
      - AGDISTIS_CONTEXT=False
  mag-ja:
    image: aksw/agdistis:latest
    networks:
      - neamt-net
    profiles: ["mag"]
    # This port mapping is being used by GERBIL (for neamt server only)
    ports:
      - 6136:8080
    volumes:
      # mount index
      - ./data/mag_data/indexdbpedia_ja_2016:/usr/local/tomcat/index
    mem_limit: 8g
    restart: always
    environment:
      - AGDISTIS_NODE_TYPE=http://ja.dbpedia.org/resource/
      - AGDISTIS_EDGE_TYPE=http://dbpedia.org/ontology/
      - AGDISTIS_BASE_URI=http://dbpedia.org
      - AGDISTIS_CONTEXT=False
  mag-nl:
    image: aksw/agdistis:latest
    networks:
      - neamt-net
    profiles: ["mag"]
    # This port mapping is being used by GERBIL (for neamt server only)
    ports:
      - 6137:8080
    volumes:
      # mount index
      - ./data/mag_data/indexdbpedia_nl_2016:/usr/local/tomcat/index
    mem_limit: 8g
    restart: always
    environment:
      - AGDISTIS_NODE_TYPE=http://nl.dbpedia.org/resource/
      - AGDISTIS_EDGE_TYPE=http://dbpedia.org/ontology/
      - AGDISTIS_BASE_URI=http://dbpedia.org
      - AGDISTIS_CONTEXT=False
  redis:
    profiles: ["redis"]
    image: redis:7 # https://hub.docker.com/_/redis/
    command: ['redis-server', '--save', '60', '1', '--loglevel', 'warning', '--maxmemory', '24gb', '--maxmemory-policy', 'allkeys-lru']
    restart: always
    ports:
      - 6379:6379
    networks:
      - neamt-net
    volumes:
      - ./cache:/data
networks:
  neamt-net:
