version: "3.3"

services:
# Main service
  naive-eamt:
    image: naive-eamt
    volumes:
      # Copy code
      - ./start.py:/neamt/start.py
      - ./component:/neamt/component
      - ./util:/neamt/util
      - ./logs:/neamt/logs
      # Copy config
      - ./configuration.ini:/neamt/configuration.ini
      # Mount the downloaded data directory(s)
      - ./data:/neamt/data
    ports:
      - 6100:80
    networks:
      - neamt-net
  # Libre Translate service
  libretranslate:
    image: libretranslate
    restart: unless-stopped
    profiles: ["libre_mt"]
    ports:
      - 6120:5000
  # MAG services with relevant parameters
  mag-en:
    image: aksw/agdistis:latest
    networks:
      - neamt-net
    profiles: ["mag"]
    volumes:
      # mount index
      - ./data/mag_data/indexdbpedia_en_2016:/usr/local/tomcat/index
      # mount context
      - ./data/mag_data/index_bycontext_en:/usr/local/tomcat/index_bycontext
    mem_limit: 8g
    restart: always
    environment:
      - AGDISTIS_NODE_TYPE=http://dbpedia.org/resource/
      - AGDISTIS_EDGE_TYPE=http://dbpedia.org/ontology/
      - AGDISTIS_BASE_URI=http://dbpedia.org
      - AGDISTIS_CONTEXT=True
  mag-de:
    image: aksw/agdistis:latest
    networks:
      - neamt-net
    profiles: ["mag"]
    volumes:
      # mount index
      - ./data/mag_data/indexdbpedia_de_2016:/usr/local/tomcat/index
      # mount context
      - ./data/mag_data/index_bycontext_de:/usr/local/tomcat/index_bycontext
    mem_limit: 8g
    restart: always
    environment:
      - AGDISTIS_NODE_TYPE=http://de.dbpedia.org/resource/
      - AGDISTIS_EDGE_TYPE=http://dbpedia.org/ontology/
      - AGDISTIS_BASE_URI=http://dbpedia.org
      - AGDISTIS_CONTEXT=True
  mag-fr:
    image: aksw/agdistis:latest
    networks:
      - neamt-net
    profiles: ["mag"]
    volumes:
      # mount index
      - ./data/mag_data/indexdbpedia_fr_2016:/usr/local/tomcat/index
    mem_limit: 8g
    restart: always
    environment:
      - AGDISTIS_NODE_TYPE=http://fr.dbpedia.org/resource/
      - AGDISTIS_EDGE_TYPE=http://dbpedia.org/ontology/
      - AGDISTIS_BASE_URI=http://dbpedia.org
      - AGDISTIS_CONTEXT=False
  mag-es:
    image: aksw/agdistis:latest
    networks:
      - neamt-net
    profiles: ["mag"]
    volumes:
      # mount index
      - ./data/mag_data/indexdbpedia_es_2016:/usr/local/tomcat/index
    mem_limit: 8g
    restart: always
    environment:
      - AGDISTIS_NODE_TYPE=http://es.dbpedia.org/resource/
      - AGDISTIS_EDGE_TYPE=http://dbpedia.org/ontology/
      - AGDISTIS_BASE_URI=http://dbpedia.org
      - AGDISTIS_CONTEXT=False
      
networks:
  neamt-net: