version: '3'
services:
  qa_wrappers:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: qa-wrappers
    # network_mode: host
    ports:
      - ${PORT}:${PORT}
    command: uvicorn start:app --reload --host 0.0.0.0 --port=${PORT}
